### ISSUE TITLE
while installing on ubuntu gives wxpython error

### ISSUE THREAD

**Issue by kaushikCanada** [NeuroTechX/EEG-ExPy#119]
## ℹ Computer information

- Platform OS (e.g Windows, Mac, Linux etc): 
- Python Version:
- Brain Interface Used (e.g Muse, OpenBCI, Notion etc):

## 📝 Provide detailed reproduction steps (if any)

1. …Linux
2. …Synthetic
3. …python 3.7

### ✔️ Expected result
installed
_What is the expected result of the above steps?_

### ❌ Actual result
Successfully built gdown psychopy sphinx-gallery pylsl questplus esprima future javascripthon macropy3 moviepy proglog pygatt
Failed to build wxPython

ERROR: Command errored out with exit status 1:
   command: /home/kaushik/miniconda3/envs/eeg-notebooks/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3f0_asj7/wxpython_33c1d864ee3a4b86beeeef42b55d0a39/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3f0_asj7/wxpython_33c1d864ee3a4b86beeeef42b55d0a39/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7o3_p5m5
       cwd: /tmp/pip-install-3f0_asj7/wxpython_33c1d864ee3a4b86beeeef42b55d0a39/
  Complete output (42 lines):
  running bdist_wheel
  running build
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.
  
  "/home/kaushik/miniconda3/envs/eeg-notebooks/bin/python" -u build.py build
  Will build using: "/home/kaushik/miniconda3/envs/eeg-notebooks/bin/python"
  3.7.10 (default, Jun  4 2021, 14:48:32)
  [GCC 7.5.0]
  Python's architecture is 64bit
  cfg.VERSION: 4.1.1
  
  Running command: build
  Running command: build_wx
  wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
  Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
  /tmp/pip-install-3f0_asj7/wxpython_33c1d864ee3a4b86beeeef42b55d0a39/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking for toolkit... gtk
  checking for gcc... no
  checking for cc... no
  checking for cl.exe... no
  configure: error: in `/tmp/pip-install-3f0_asj7/wxpython_33c1d864ee3a4b86beeeef42b55d0a39/build/wxbld/gtk3':
  configure: error: no acceptable C compiler found in $PATH
  See `config.log' for more details
  Error running configure
  ERROR: failed building wxWidgets
  Traceback (most recent call last):
    File "build.py", line 1510, in cmd_build_wx
      wxbuild.main(wxDir(), build_options)
    File "/tmp/pip-install-3f0_asj7/wxpython_33c1d864ee3a4b86beeeef42b55d0a39/buildtools/build_wxwidgets.py", line 373, in main
      "Error running configure")
    File "/tmp/pip-install-3f0_asj7/wxpython_33c1d864ee3a4b86beeeef42b55d0a39/buildtools/build_wxwidgets.py", line 85, in exitIfError
      raise builder.BuildError(msg)
  buildtools.builder.BuildError: Error running configure
  Finished command: build_wx (0.293s)
  Finished command: build (0.293s)
  Command '"/home/kaushik/miniconda3/envs/eeg-notebooks/bin/python" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxPython

_What is the actual result of the above steps?_

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S (Windows) / Shift+Command+4 (MacOS) and then just paste them directly into the form_

**Comment by JohnGriffiths** [comment]
Hi Kaushik. 

Thanks for this. 

Just to confirm: this was the result you got when running 

`pip install -e .` 

in the eeg-notebooks folder?

ta.

**Comment by kaushikCanada** [comment]
Yea that is the one.

**Comment by ErikBjare** [comment]
Try passing `--find-links=https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/` to the pip install command, or install a compiler toolchain (as the error complains about not finding one).

**Comment by kaushikCanada** [comment]
Wbat is yhe compiler toolchain? I thought u just do the pip install

**Comment by ErikBjare** [comment]
@kaushikCanada See for example: https://stackoverflow.com/a/19816655/965332

**Comment by JohnGriffiths** [comment]
The `wxpython' installation issue is solved in the latest documentation ( basically, use conda rather than pip for this ). 

c.f. here

https://github.com/NeuroTechX/eeg-notebooks/issues/138

and the installation instructions ( `wxpython` is in the conda create line )

https://neurotechx.github.io/eeg-notebooks/getting_started/installation.html#installing-the-python-library
