### ISSUE TITLE
NTCS Consent Form Internal Testing

### ISSUE THREAD

**Issue by JohnGriffiths** [NeuroTechX/EEG-ExPy#130]
We are finalizing internal testing for the NTCS-Phase1 consent process and experiment instructions. 

**Everyone please take the time to go through the process below and provide feedback.** 

Kudos to @tmorshed for setting all of this up. 

## NTCS Phase 1 Internal Testing Instructions

As you know, we are kicking off a new initiative for public EEG experimentation at home using common market-available EEG headsets and eeg-notebooks, in collaboration with OpenBCI and NeuroTechX.

So, we need your help to user-test the consent and data acquisition form. 

Feel free to use fake health information and fake data (like this empty zip file)

The process is all focused on a single REDCap form. 

First, you read through the informed consent form. 

Second, you answer a quiz based on the consent form (to ensure comprehension), and then you provide your email address. 

You will receive the instructions for the experimental paradigm and the software/hardware considerations in your inbox. 

You will also receive your unique link to upload the recorded EEG file. 

Click on the link, answer the final questions, and upload any file (e.g. empty.zip). 

If you have extra time later, feel free to click on the link again, this time with different entries (e.g. missing quiz questions on purpose, or choosing "I don't consent"! The point is just to test the form under all circumstances.

**The REDCap form (the actual study) is found at [is.gd/ntcs2021test](https://is.gd/ntcs2021test)**

**And please rate your experience at [forms.gle/Vi8CuHMJbQuiTUxx7](https://forms.gle/Vi8CuHMJbQuiTUxx7)**

Thank you so much for your help! 

Please feel free to drop any questions w.r.t. the form on this issue thread.

**Comment by AyrusCode** [comment]
On final page (Thank you page) with two options, it is possible to download responses via Option 2 but no place to enter email if person so chooses to have their responses emailed to them for Option 1.

![image](https://user-images.githubusercontent.com/9661655/133685125-a83570ee-8d7c-4d1c-8e6e-669f24a91f96.png)

**Comment by HVjay** [comment]
Received an email for the study consent form. However, did not receive the form with experiment instructions and link to upload the data. 
![image](https://user-images.githubusercontent.com/42661185/133692832-1850752f-3fab-41d8-a77f-b69df67a0851.png)

**Comment by oreHGA** [comment]
feedback for consent form
- would it be possible to add a link back to the details about the study in the previous page (for someone who want's to go back and check)
![image](https://user-images.githubusercontent.com/13490968/133937097-af63a019-64e0-4cd7-b8a4-b125c08766e6.png)
- nit: change from "i" to "you" to stay consistent with the other questions
![image](https://user-images.githubusercontent.com/13490968/133937318-43ec42e9-d663-4eae-8303-dd0b77f53c3c.png)

- at the end of the survey page, would it be possible to the "NTCS Challenge Page"? 
- so i put in a bunch of wrong answers and got to this page... Is it possible to link to the start of the page? Or tell them what answers were wrong? 
![image](https://user-images.githubusercontent.com/13490968/133938225-b769bc9b-2f2f-4dfd-a68c-7e8f9fc5f1f3.png)

**Comment by JohnGriffiths** [comment]
Summarizing dev meeting discussion on this: 


On Redcap page:

- 'Option 1: Enter your e-mail address' line on final page doesn't have an option to enter. Fix this ( we already have it? )
- Add 'go to previous page' links
- Make the 'we are unable to continue' message a bit more polite and explanatory
- Add link to NTCS challenge page at end ( + other parts? ) of survey
- ( Update NTCS challenge page! -> Joe/Richard ) 
- Correct the 'I' error above


In email:

- Check: latency of e-mail sending. Harris says it took a day to receive his. 


- 'run notebooks.py' -> needs updating to cli cmds
- link to the docs page on running an experiment more clearly 
- add extra step saying we will be in touch we will notify you with update, including when the public data will be available etc

- finalized experiment instructions = N170 experiment, 10 x 5 min blocks, can rest between blocks, but do in one session. 
- [ total time commitment: installation, up to 1hr; run experiment: 1hr ]

**Comment by tmorshed** [comment]
**REDCap updates:**
- [X] 'Option 1: Enter your e-mail address' line on the final page doesn't have an option to enter. Fix this 
 - **A:** We already have it. Will fix the text on the last page. Updated the text now, it tells them 
- [X] Add 'go to previous page' links
- [x] Make the 'we are unable to continue' message a bit more polite and explanatory
 - **Updated text:** "Unfortunately, we cannot go forward with your e-consent process as you have not received a perfect score on the information quiz".
- [x] Add a link to the NTCS challenge page at the end of the successful survey

**Comment by oreHGA** [comment]
Thanks everyone for jumping on to test. Think we can close this now. looking forward to our launch soon :)
