### ISSUE TITLE
Add option for signal quality checker when running experiments 

### ISSUE THREAD

**Issue by hvjay** [NeuroTechX/EEG-ExPy#135]
When running experiments, users should be able to verify the quality of their signal right before starting an experiment.

**Comment by oreHGA** [comment]
Hi @HVjay hope you're doing well! Wanted to find out if you were able to make headway with this? Looking through I'm thinking a flow here will be:

- user runs `eegnb runexp`
- A little prompt comes up letting the user know that "Signal quality" will be recorded & a character to press to "skip and begin recording"
- show a message & trigger the experiment right after

**Comment by oreHGA** [comment]
*fingers-crossed* looking to focus on this now and link to PR
