### ISSUE TITLE
Clearing old examples

### ISSUE THREAD

**Issue by JadinTredup** [NeuroTechX/EEG-ExPy#14]
We should go through the old examples and delete the ones that reference the old API. 

@JohnGriffiths are there any reasons we need to keep any of these examples?

**Comment by JohnGriffiths** [comment]
No, they can go. Or, better, be updated.

The place for scratch / temp / possibly to be removed things is the sandbox folder.

**Comment by JohnGriffiths** [comment]
resuming and executing this now. will also put together a downloader for the compiled notebooks from the website.

**Comment by JohnGriffiths** [comment]
done. 

summary: 

- removed .ipynb files in visual n170, visual p300, and visual ssvep folders

- the place for old .ipynbs is the sandbox folder

- however there are still some .ipynbs in the visual cueing folder. I'm not sure we want to remove those yet. 



l
