### ISSUE TITLE
The SSVEP data collected on openbci can not detect the peak value of 20Hz

### ISSUE THREAD

**Issue by znnnnn1** [NeuroTechX/EEG-ExPy#17]
Does the ssevp data collected by openbci and muse have the same effect

**Comment by JadinTredup** [comment]
@znnnnn1 it does in theory but depending on your setup, the OpenBCI device might have a noisier signal. Can you share the results you received?

**Comment by JadinTredup** [comment]
@znnnnn1 did you still want to discuss this further or can I close the issue?
