### ISSUE TITLE
Builds fail on Linux (missing liblsl)

### ISSUE THREAD

**Issue by ErikBjare** [NeuroTechX/EEG-ExPy#187]
Getting issues with missing liblsl: https://github.com/NeuroTechX/eeg-notebooks/runs/6920267569

Likely due to: https://github.com/labstreaminglayer/liblsl-Python/blob/4ac07fd67d64691bfbee32270c624f4dc8f391fe/README.md#linux-binaries-deprecated

Was gonna pin the dependency, but weirdly, we should be getting 1.10.5?: https://github.com/alexandrebarachant/muse-lsl/blob/master/setup.py#L51

**Comment by oreHGA** [comment]
Should be fixed by #170
