### ISSUE TITLE
Hello, I have a basic question about another project

### ISSUE THREAD

**Issue by Shahin-rmz** [NeuroTechX/EEG-ExPy#203]
Hello, I am interested about [Neurodoro](https://awesomeopensource.com/project/NeuroTechX/neurodoro) project. As seen, it is not maintained any more. want to know why it is not maintained and if there are any reasons behind stopping maintaining it.
Thanks

**Comment by oreHGA** [comment]
Hey @Shahin-rmz thanks for reaching out. Neurodoro is out of the scope of the `eeg-notebooks` project. Can you post this on the [NeurotechX](https://neurotechx.com/) slack #neurodoro channel instead
