### ISSUE TITLE
N170 experiment doesn't work

### ISSUE THREAD

**Issue by Liam-Noah** [NeuroTechX/EEG-ExPy#204]
## ℹ Computer information

- Platform OS (e.g Windows, Mac, Linux etc):  Windows
- Python Version: 3.7
- Brain Interface Used (e.g Muse, OpenBCI, Notion etc): muse2

## 📝 Provide detailed reproduction steps (if any)

run N170 experiment https://neurotechx.github.io/eeg-notebooks/auto_examples/visual_n170/00x__n170_run_experiment.html#sphx-glr-auto-examples-visual-n170-00x-n170-run-experiment-py

after this line n170.present(duration=record_duration, eeg=eeg_device, save_fn=save_fn)
computer freezes 
I use command line python, and jupyter notebook , the results are the same

I get a black screen, actually 2 of them pyschopy python windows
computer stops working properly have to push the shutdown button

in C:\Users\...\eeg-notebooks\eeg-notebooks\eegnb\experiments\visual_n170\n170.py
it stops at this line mywin = visual.Window([1600, 900], monitor="testMonitor", units="deg", fullscr=True) 

update : I've change both function to not require full screen. line 40 and 112. and it works better
but now I have multiple screens (3) showing up after I press down space
and then at the end of the experiment the file doesn't save

update2 : running it in jupter notebook solved the issue after applying the fix from above

### ✔️ Expected result

_What is the expected result of the above steps?_
I guess I should see a window and images appearing

### ❌ Actual result

_What is the actual result of the above steps?_

see above

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S (Windows) / Shift+Command+4 (MacOS) and then just paste them directly into the form_

**Comment by oreHGA** [comment]
Hey @Liam-Noah could you try recreating a new environment and then re-installing eeg-notebooks.

When this is done, in your interactive terminal, try running the following to validate the experiment presentation works:
```
from eegnb.experiments.visual_n170 import n170
n170.present(duration=10)
```

Let us know if you still run into issues. The example isn't fetching eeg just so we can focus on the stimulus presentation bit.
