### ISSUE TITLE
Research showing the influence of the used SSVEP pattern image

### ISSUE THREAD

**Issue by SjoerdTimovanVliet** [NeuroTechX/EEG-ExPy#206]
Dear Sir/madam

Most SSVEP research use on/off switching. However, several of my professors stated that the influence of showing the pattern image with an on/off stimuli frequency must be stated in research the use of your platform. However, most research only use On/OFF stimulation by showing a white and then a black rectangle. Could you provide me with any source information regarding this pattern image that I could use in my research?
It would be greatly appreciated.

Best regards,

Sjoerd

**Comment by JohnGriffiths** [comment]
Hi Sjoerd. 

Great to hear from you, happy to help on this.

The SSVEP experiment in eeg-notebooks uses gratings, not a rectangle.  

The code lines defining the stimuli and timings for this are here:

https://github.com/NeuroTechX/eeg-notebooks/blob/a22501228677df0f968c49a0a699207380b1bd50/eegnb/experiments/visual_ssvep/ssvep.py#L27

Is that the info you're after?

**Comment by oreHGA** [comment]
Hey @SjoerdTimovanVliet , closing this for now, but feel free to re-open if you'd like to continue to conversation / have more questions
