### ISSUE TITLE
Neurosity crown supported in code, not yet listed in doc

### ISSUE THREAD

**Issue by jkosciessa** [NeuroTechX/EEG-ExPy#268]
[rendered page](https://neurotechx.github.io/EEG-ExPy/getting_started/streaming.html)
[markdown](https://github.com/NeuroTechX/EEG-ExPy/blob/master/doc/getting_started/streaming.md)

## 📝 Provide a description of requested docs changes

add Neurosity crown to list of supported devices

_What is the purpose and what should be changed?_

Crown appears to be supported [in the code](https://github.com/NeuroTechX/EEG-ExPy/blob/e03c52dd904d5d20f945ecb16ef12c03f3d7f2f5/eegnb/devices/eeg.py#L47)

**Comment by oreHGA** [comment]
Thanks for flagging! Just updated this - https://neurotechx.github.io/EEG-ExPy/getting_started/streaming.html#neurosity-crown
