### ISSUE TITLE
run n170 experiment

### ISSUE THREAD

**Issue by JohnGriffiths** [NeuroTechX/EEG-ExPy#28]
After you have have run through the first 'good first issue' and completed [installation](https://github.com/NeuroTechX/eeg-notebooks/issues/27), the next thing to do is to run one of the experiments. 

Note, this only applies to users/developers with access to an EEG device. 

As with the installation issue, we would like to gather feedback and any errors encountered from this process. 

Please follow through the instructions [here](https://neurotechx.github.io/eeg-notebooks/getting_started/running_experiments.html). Be sure to select the correct EEG device, choose the `visual N170` experiment, and for this test run, just enter '30' (30 seconds) for the `duration` option. 

Please leave comments on this thread with any issues encountered, or suggestions for improvement, from your experience of this process.

**Comment by nicolas-barabino** [comment]
Hello everybody. I got it to run (had to use Python 3.7 and psychopy-2021.2.3) and when I get data the CSV file is missing the last column in the firsts rows 
please see the attachment, I also include the one from the example with the last column Marker0). @JohnGriffiths mentioned on NTX slack that other people where having this problem too. Thanks 

 (![image](https://user-images.githubusercontent.com/65022946/147775203-2d764051-d19d-4da7-b536-71cac58d199b.png) 
<img width="400" alt="timestamps, TP9, AF7, AF8, TP10, Right AUX" src="https://user-images.githubusercontent.com/65022946/147775307-7510e08f-5774-4498-8b90-39334d0e2ec2.png">

**Comment by tmorshed** [comment]
Closing as is stale.
Please reopen if necessary
