### ISSUE TITLE
make html on mac throws error

### ISSUE THREAD

**Issue by kylemath** [NeuroTechX/EEG-ExPy#4]
still working on debug, but to keep track of bugs here is one, as @JohnGriffiths suspected, may not work on mac natively:

(venv) Kyles-MacBook-Pro:doc kylemathewson$ make html
/bin/sh: sphinx-build: command not found
make: *** [html] Error 127

**Comment by JohnGriffiths** [comment]
Thanks for the info. 

Open to suggestions re: doc build support on mac. Haven't looked into it. 

Currently things work for linux, and indirectly for windows visa WSL (which is how I've been doing it so far).

---

Looking at the error you have: it sounds like it's read the `Makefile` correctly but is stumbling on `sphinx` .

Do you definitely have the `sphinx` etc python libraries installed in that env?

**Comment by kylemath** [comment]
ok I figured it out, I hadn't install any packages because of https://github.com/NeuroTechX/eeg-notebooks/issues/3, so I removed that dependency from the .txt and installed, now this runs,
