### ISSUE TITLE
Support newer Python versions

### ISSUE THREAD

**Issue by ErikBjare** [NeuroTechX/EEG-ExPy#50]
There seems to be a lot of issues when installing on other Python versions than 3.7, since I have a pretty extensive history of battling issues like these I thought I might give it a shot (especially now that we have a CI pipeline).

Documenting known issues here:

 - [x] Installing pywinhook on Windows on Python 3.9 requires extra build deps (swig, VS C++ tools) due to no prebuilt wheels being available on PyPI
    - Fixed by referencing wheels built elsewhere in requirements.txt
 - [x] Build errors for numpy/pandas
    - It seems this is merely due to the versions in requirements.txt being old. Using newer versions works just fine. (another reason for #22)
 - [ ] tables 3.6.1 has no wheels available for Python 3.9 on platforms other than Linux (see: https://github.com/NeuroTechX/eeg-notebooks/actions/runs/400623523)

**Comment by JohnGriffiths** [comment]
We'll aim to address newer Python version support with high priority. 

However, it is quite tricky to make quick progress on as we need to co-ordinate multiple people with access to different OSs etc. 
(as we observed at the Dec brainhack)

**Comment by JohnGriffiths** [comment]
Related: https://github.com/NeuroTechX/eeg-notebooks/issues/29
