### ISSUE TITLE
Error:name 'fetch_dataset' is not defined”)

### ISSUE THREAD

**Issue by akazemian** [NeuroTechX/EEG-ExPy#69]
I was trying to run the N170 experiemnt from https://neurotechx.github.io/eeg-notebooks/experiments/vn170.html but when I run the code block for downloading the data, I get an error saying “name 'fetch_dataset' is not defined”. Which makes me think Im missing a library and I dont know where to find it. I’m on linux and I’ve already installed the requirements and libraries. I would appreciate any thoughts from anyone who may or may not have had a similar issue. When installing the libraries on my virtual env, I did get a build error for wxWidgets and Phoenix but everything else worked fine.

Code:

`eegnb_data_path = os.path.join(os.path.expanduser('~/'),'.eegnb', 'data')`

`n170_data_path = os.path.join(eegnb_data_path, 'visual-N170', 'eegnb_examples')`

`if not os.path.isdir(n170_data_path):`

      `fetch_dataset(data_dir=eegnb_data_path,experiment='visual-N170', site='eegnb_examples');`

`subject = 1`

`session = 1`

`raw = load_data(subject,session, experiment='visual-N170', site='eegnb_examples', device_name='muse2016', data_dir = eegnb_data_path) `

**Comment by JadinTredup** [comment]
fetch_dataset is a function within EEG Notebooks. Did you run the import `from eegnb.datasets import fetch_dataset` at the start of the script?
