### ISSUE TITLE
Add code coverage analysis

### ISSUE THREAD

**Issue by ErikBjare** [NeuroTechX/EEG-ExPy#77]
Another improvement to the CI pipeline.

We don't have much in the way of tests, but we do have the auto examples which run a fair bit of the code. It'd be nice to know exactly which code is somewhat tested in CI, and which isn't (and when new code is added, how well covered it is by tests/examples). 

This should be easy enough to do with `coverage.py`.

**Comment by JohnGriffiths** [comment]
Agree- the examples have a very test-like function but that isn't explicitly documented. Coverage tracking would be great to include

**Comment by ErikBjare** [comment]
I added coverage for `*.ipynb` notebooks in my thesis repo the other day, but I'm not sure how to do it for the `auto_examples`... 

I gave it a shot in https://github.com/NeuroTechX/eeg-notebooks/pull/88, but it's not ready yet.
