### ISSUE TITLE
Raise minimum supported Python to 3.7 (at least)

### ISSUE THREAD

**Issue by ErikBjare** [NeuroTechX/EEG-ExPy#90]
There are a few things I've been working on where I'd really benefit from the minimum version being raised to 3.7 (time_ns, dataclasses, etc.)

Are there any blockers for this? 

For the record: I've been running 3.8 just fine locally (although since https://github.com/NeuroTechX/eeg-notebooks/pull/32 is unmerged, that might suggest there are some remaining issues, but we could just go ahead and merge it and wait with 3.9).

For discussion around maximum supported version, see #50

**Comment by JohnGriffiths** [comment]
I approve of this. I think 3.7 now fixes a lot of the pywinhook issues that initially promoted choice of 3.6
